### ISSUE TITLE
Failures on start

### ISSUE THREAD

**Issue by r86m** [S1SYPHOS/Gulp-Kirby-Starter-Kit#13]
Hey,

i try to start but i got two errors... 

1) on composer create-project  ... .

[InvalidArgumentException]                                                     
  Could not find package s1syphos/gulp-kirby-starter-kit with stability stable. 

2) If i just skip this composer task and only pull your repo and try "npm start":

 127.0.0.1:62413 [200]: / - Uncaught Error: Class 'Kirby' not found in /Users/XYZ/MY_PROJECT/index.php:25

Any ideas what i'm doing wrong ?

**Comment by S1SYPHOS** [comment]
When downloading / cloning this, be sure to `composer update && npm i` to get the latest dependency packages - if the problem persists however, I'm glad to help!

Just let me know how it goes 🙂 

**Update:**
Where are you running this, via PHP server, some other setup with a webserver?

**Comment by r86m** [comment]
hey, thx for fast answer

composer update helped ;) 
if i start with php server everything looks good, but if i try with "npm start" i cannot access the panel, i just getting an error: 
"The Panel cannot connect to the API" 

i'm happy that it runs over php server, thank you very much for fast answer ;)

**Comment by S1SYPHOS** [comment]
@pivster86 Regarding the composer error: I have to release a stable version  first - unless you set your `minimum-stability` accordingly ..

For a more versatile development setup, check the Vagrant project mentioned in the README 🙂
