### ISSUE TITLE
Browserlist

### ISSUE THREAD

**Issue by schikunow** [S1SYPHOS/Gulp-Kirby-Starter-Kit#4]
After i'm starting the php server with npm start following message appears: 

> Replace Autoprefixer browsers option to Browserslist config.
>   Use browserslist key in package.json or .browserslistrc file.
> 
>   Using browsers option cause some error. Browserslist config 
>   can be used for Babel, Autoprefixer, postcss-normalize and other tools.
> 
>   If you really need to use option, rename it to overrideBrowserslist.
> 
>   Learn more at:
>   https://github.com/browserslist/browserslist#readme
>   https://twitter.com/browserslist

**Comment by S1SYPHOS** [comment]
Thank you - I'll have a look at this and eventually replace the current setup.

Cheers!

**Comment by schikunow** [comment]
> Thank you - I'll have a look at this and eventually replace the current setup.
> 
> Cheers!

Thank you too!
